### ISSUE TITLE
ember test fails

### ISSUE THREAD

**Issue by mzagaja** [MAPC/neighborhood-drawing-tool-client#1]
After running:
```
git clone
npm install
bower install
ember test
```
I get the following error when running the test and `ember serve`

```
Build failed.
ENOENT: no such file or directory, lstat '/Users/mzagaja/Developer/knowplace-client/tmp/funnel-input_base_path-GTHi19Qe.tmp/bower_components/materialize/dist/font/roboto/Roboto-Thin.woff2'
Error: ENOENT: no such file or directory, lstat '/Users/mzagaja/Developer/knowplace-client/tmp/funnel-input_base_path-GTHi19Qe.tmp/bower_components/materialize/dist/font/roboto/Roboto-Thin.woff2'
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at symlink (/Users/mzagaja/Developer/knowplace-client/node_modules/symlink-or-copy/index.js:79:26)
    at Function.symlinkOrCopySync [as sync] (/Users/mzagaja/Developer/knowplace-client/node_modules/symlink-or-copy/index.js:65:5)
    at Funnel._copy (/Users/mzagaja/Developer/knowplace-client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:252:17)
    at Funnel.processFile (/Users/mzagaja/Developer/knowplace-client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:243:8)
    at Funnel.processFilters (/Users/mzagaja/Developer/knowplace-client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:154:12)
    at Funnel.build (/Users/mzagaja/Developer/knowplace-client/node_modules/ember-cli/node_modules/broccoli-funnel/index.js:118:10)
    at /Users/mzagaja/Developer/knowplace-client/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/mzagaja/Developer/knowplace-client/node_modules/rsvp/dist/rsvp.js:525:12)
```
Sounds like a font file is missing from the repo?

**Comment by allthesignals** [comment]
Thanks @mzagaja, sorry about that, this is related to https://github.com/mike-north/ember-cli-materialize/issues/327, which I've reported. There is a fix, it is documented in my comments there. I don't know why I failed to implement a fix, but it's related to versioning issues with dependencies.

**Comment by allthesignals** [comment]
Try `bower install materialize#0.97.1`
