### ISSUE TITLE
npm install fails on node-gyp rebuild

### ISSUE THREAD

**Issue by mzagaja** [MAPC/neighborhood-drawing-tool-client#2]
Attempting to rebuild node-gyp on my Macbook Pro throws the following error:

```
12 warnings and 17 errors generated.
make: *** [Release/obj.target/validation/src/validation.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/8.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mzagaja/GitHub/knowplace-client/node_modules/utf-8-validate
gyp ERR! node -v v8.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.1.0 (node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.1.0 (node_modules/utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

I have tried the following advice from https://github.com/nodejs/node-gyp/issues/809.

1. Try different versions of node.js
2. Upgrade XCode to the latest version
3. Re-agree to the XCode License Agreement
4. Retry installing node.js
5. `brew unlink libtools` and `brew link libtools`
6. `brew update && brew upgrade`
7. Uninstall and reintsall node.js

**Comment by mzagaja** [comment]
The solution ended up being:

1. Set python path to `npm config set python /usr/bin/python2.7`
2. `rm -rf ~/.node-gyp`
3. `rm -rf node_modules` from the knowplace-client directory
4. `rm -rf ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/*`
5.  `sudo npm install`
